name: "Blog of Yungeng Xu"
description: "Web Front-End Blog by Yungeng Xu"

url: "https://xygcxy.github.io/"

timezone: Asia/Shanghai

paginate: 20

highlighter: pygments

<<<<<<< HEAD
excerpt_separator: "\n\n"

safe:        false
watch:       false    # deprecated
server:      false    # deprecated
host:        0.0.0.0
port:        4000
baseurl:     /
url:         https://xygcxy.github.com/xyg_blog/
lsi:         false

=======
markdown: rdiscount
permalink: pretty
>>>>>>> 60501f5de06f1bb7adbde1d10816b13cd639ac0d
