name: "Blog of Yungeng Xu"
description: "Web Front-End Blog by Yungeng Xu"

url: "https://xygcxy.github.io/"

timezone: Asia/Shanghai

paginate: 20

highlighter: pygments

markdown: rdiscount
permalink: pretty
